=== Chris-Iv/Homework/Database Applications/XML-Basic-Concepts-Homework/XML-Basic-Concepts-Homework/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:students="http://www.students.org/students" 
           attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           targetNamespace="http://www.students.org/students" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="gender" type="xs:string" />
              <xs:element name="birth-date" type="xs:string" />
              <xs:element name="phone-number" type="xs:string" minOccurs="0" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="university" type="xs:string" />
              <xs:element name="speciality" type="xs:string" />
              <xs:element name="faculty-number" type="xs:positiveInteger" minOccurs="0" />
              <xs:element name="exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="exam-name" type="xs:string" />
                    <xs:element name="date-taken" type="xs:string" />
                    <xs:element name="grade" type="xs:decimal" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="endorsements" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="author" />
                    <xs:element name="author-email" />
                    <xs:element name="endorsement-date" />
                    <xs:element name="endorsement-text" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Chris-Iv/Homework/Database Applications/XML-Basic-Concepts-Homework/XML-Basic-Concepts-Homework/students-with-namespace.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students:students xmlns:students="http://www.students.org/students"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.students.org/students students.xsd">
  <students:student>
    <students:name>Pesho Peshev</students:name>
    <students:gender>Male</students:gender>
    <students:birth-date>06.01.1990</students:birth-date>
    <students:phone-number>0891715253</students:phone-number>
    <students:email>pesho@gmail.com</students:email>
    <students:university>Software University</students:university>
    <students:speciality>Programming</students:speciality>
    <students:faculty-number>001</students:faculty-number>
    <students:exams>
      <students:exam-name>C# Basics</students:exam-name>
      <students:date-taken>25.01.2015</students:date-taken>
      <students:grade>5.10</students:grade>
    </students:exams>
  </students:student>
  <students:student>
    <students:name>Gosho Goshev</students:name>
    <students:gender>Male</students:gender>
    <students:birth-date>15.04.1980</students:birth-date>
    <students:phone-number>0885534899</students:phone-number>
    <students:email>gosho@gmail.com</students:email>
    <students:university>Software University</students:university>
    <students:speciality>Programming</students:speciality>
    <students:faculty-number>003</students:faculty-number>
    <students:exams>
      <students:exam-name>PHP Basics</students:exam-name>
      <students:date-taken>13.19.2014</students:date-taken>
      <students:grade>5.35</students:grade>
    </students:exams>
  </students:student>
</students:students>

=== Chris-Iv/Homework/Database Applications/XML-Basic-Concepts-Homework/XML-Basic-Concepts-Homework/students.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:schemaLocation="http://www.students.org/students students.xsd">
  <student>
    <name>Pesho Peshev</name>
    <gender>Male</gender>
    <birth-date>06.01.1990</birth-date>
    <phone-number>0891715253</phone-number>
    <email>pesho@gmail.com</email>
    <university>Software University</university>
    <speciality>Programming</speciality>
    <faculty-number>001</faculty-number>
    <exams>
      <exam-name>C# Basics</exam-name>
      <date-taken>25.01.2015</date-taken>
      <grade>5.10</grade>
    </exams>
  </student>
  <student>
    <name>Gosho Goshev</name>
    <gender>Male</gender>
    <birth-date>15.04.1980</birth-date>
    <phone-number>0885534899</phone-number>
    <email>gosho@gmail.com</email>
    <university>Software University</university>
    <speciality>Programming</speciality>
    <faculty-number>003</faculty-number>
    <exams>
      <exam-name>PHP Basics</exam-name>
      <date-taken>13.19.2014</date-taken>
      <grade>5.35</grade>
    </exams>
  </student>
</students>
